### ISSUE TITLE
DAWN-466 ⁃ Remove explicit scoping from transactions

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1062]
# Scope is not the User's concern. 

This closes #1040 

Previously a user would have to guess or have tools infer "scopes" for a transactions.  On the occasion that this inference or guesswork would fail, users would have a pretty bad time trying to figure out the proper arcane scopes to make things work.  There was basically no way for scopes to create anything other than a negative user experience if the user experienced them at all.  As a result, we have move the determination of scopes into the responsibility of a block producer.  This simplifies the guarantees that each party in the network is making:
  * Users: guarantee that this is the set of actions they desire and that the supplied signatures + permissions grant authority to perform those actions
  * Producers: guarantee that blocks are scheduled such that no parallel execution unit (shard) conflicts with another shared in terms of read/write scopes

## Tasks

 - [x] Remove read/write_scope from `transaction`
 - [x] create a first class `shard` type instead of typedef'ing as `vector<transaction_receipt>`
 - [x] add read/write scopes to `shard`
 - [x] Add ability to "record" scopes used as an alternative to enforcing scopes are known when applying transactions
 - [x] produce new blocks such that scopes can be recorded into shards properly, determining them through the "record" feature
 - [x] validate incoming blocks by only allowing access to scopes as defined by the `shard` under which the transactions are being executed
    * if a transaction accesses an unlisted scope (read or write) this should be considered an objective failure of the incoming block
 - [x] remove scope arguments/handling from `eosioc`
 - [x] clean up test cases that were manually setting scopes
 - [ ] clean up documentation and tutorials that mention scopes

**Comment by wanderingbort** [comment]
Forgot to add the requirements from the supplanted issue regarding scopes still being logically "under code" and not free standing:
- [ ] read and write scopes on a transaction become pairs of `account_name code;` and `name scope;`
- [ ] `require_write_scope` in contracts should maintain its single parameter, contracts may only write to scopes under their account so, the value of `code` is implicit
- [ ] `require_read_scope` can take an optional (defaulted to the current receiver) account name to specify which account name the read scope is under.

**Comment by blockone-syncclient** [comment]
➤ Brian Johnson commented:

When this is implemented, we will need to determine how account_history_plugin needs to function, since it was using scope to track transaction lookup (if you you do "eosioc get transactions tester1" it finds all transactions that had "tester1" in its scope).  At that time we will likely want to also make sure that solution fixes the oddity that the newaccount action that creates an account is not reported in that accounts transactions (since it isn't part of the scope, but is reported in the creator accounts transactions.

**Comment by wanderingbort** [comment]
I think we may want to record all transactions where either your account is mentioned in `actions[].authorizations` or your account was notified of any of the actions (whether you were the original recipient aka `code` or notified via wasm)  

Using scope was yet another clouding of what scope was/is.  

This would mean we would list a transaction where your accounts permission structure was used to authorize an action even if it doesn't touch data AND any action where a contract on your account could have acted.

**Comment by blockone-syncclient** [comment]
➤ Bart Wyatt commented:

#1077 PR on github

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Bart says Done
