### ISSUE TITLE
DAWN-479 ⁃ Route all native token actions through `transfer`

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1096]
# Refactoring Native Token Handling

The native contracts/actions take advantage of their privileged direct access to the database to manipulate the database entries for tokens for things like moving tokens to stake, creating accounts etc.  While these are all legitimate actions, it should be possible to only use the basic `transfer` action to accomplish this.  In doing so, we reduce the number of actions a 3rd party must monitor to have an accurate token balance to _only_ the `transfer` action and not a handful of other "implicit" withdraws/deposits. 

## Tasks
- [ ] refactor native actions which implicitly modify the eos token balance to issue inline transfer actions
  - [ ] `newaccount` implicitly withdraws initial stake from creators account
  - [ ] `lock` implicitly withdraws stake from callers account
  - [ ] `claim` implicitly deposits tokens to the callers account

## Notes
The staking mechanics are being changed by many issues and so these native calls may not be accurate when we get around to time of implementation.

**Comment by blockone-syncclient** [comment]
➤ Kevin Heifner commented:

[~bart.wyatt] I believe this has already been done via bios and updates for generic_currency and eosio.system contract.

**Comment by coreylederer** [comment]
Closing per conversation with Bart / Kevin on 2/20/2018
