### ISSUE TITLE
BFT DPOS

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#2192]
- [x] Producer Plugin should generate signatures on blocks with new all time high timestamp & blocknum
- [ ] P2P code should broadcast these signatures if they are valid for the active producer set
- [ ] Fork Database should advance the last irreversible block.
- [ ] All signatures should be kept and logged with the block transaction trace
- [ ] Double signing should be detected and reported to the system contract via a signed transaction

**Comment by bytemaster** [comment]
Today Bart, Areg, and I discussed changes that will be necessary to simplify light client validation. In particular, we would like light clients to always be able to validate block producer schedule changes with 15/21 signatures without the need for complex DPOS proofs showing indirect evidence. 

In practice the only blocks that should have less than 15 signatures available are those which are part of short-term network splits. 

The goal is to make light clients as simple and efficient as possible. There may be almost limitless light clients with a fixed cost to the main chain.

**Comment by dls-cipher** [comment]
I am confused! It appears BFT-DPOS was promised from start. Here, it seems it is not only **not** implemented today but also put on another released, but the issue is closed.
Can we reopen it so we finally get the promised BFT-DPOS in eosio or at least get more clarity why the issue has been blocked/closed?
