### ISSUE TITLE
Permission Management and Delegation

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#402]
# Motivation
Managing permissions needs to be streamlined from a user perspective so that the system can be used by contract developers to enable competitive features such as coordinated publishing of transactions authorized by multiple parties.  This is a superset of equivalent features to existing technologies such as multi-sig contracts on ethereum and other platforms.

# Sub-Tasks

- [ ] implement/clean-up `eosc` permission interface
- [ ] allow contract code to explicitly use the `owner` permission for any message
- [ ] implement basic "mult sig" contract
  - [ ] contract should allow for proposing a transaction, approving from multiple parties and explicit dispatch of an approved proposal
  - [ ] allow user to specify whether dispatch is inline or deferred
- [ ] implement "auto scope determination" as part of `eosc`
  - [ ] allow a node to infer `scope` field of a pushed transaction from execution of a signed transaction
  - [ ] allow `eosc` to query inferred `scope` from an RPC node before final signature
- [ ] Document the deployment and use of the "multi sig" contract
- [ ] Test cases

# Deprecated Issues
This will include/deprecate and therefore close the following issues:
- #185 
- #113

**Comment by wanderingbort** [comment]
shelving this for the moment to deal with milestone issues.  Basic command structure has been added to `eosc` but is not ready yet

**Comment by wanderingbort** [comment]
After playing with the new commands and setting up some permission scenarios, I realized it may be useful to add some permission options to existing commands allowing you to, for instance, use `./eosc transfer` to send EOS with something less than the `@active` authority if such a structure has been set up.

Noted in the list above

**Comment by bytemaster** [comment]
Nicely structured issue!

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

Bart:

After playing with the new commands and setting up some permission scenarios, I realized it may be useful to add some permission options to existing commands allowing you to, for instance, use ./eosc transfer to send EOS with something less than the @active authority if such a structure has been set up.

Noted in the list above

**Comment by blockone-syncclient** [comment]
➤ Corey Lederer commented:

[~bart.wyatt] Do we have tickets covering the open issues in this ticket?
