### ISSUE TITLE
[TEST] Multiple Users Reported Failing Tests

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#4927]
## Problem

Since around 2 months, multiple users were reporting test-failures.

## List of Issues

* #3842 last 6 tests failing
* #4342 - 6 tests failed
* #4079 - 6 out of 36 tests failed: is that critical?
* #4758 - Plugin and Nodeos test failed. -> closed incorrectly, blaming WSL
* #4764 - rebuild v1.1.0, make test has failed
* https://github.com/EOSIO/eos/issues/4883#issuecomment-408137129
* ... (list is incomplete)

## Possible Causes

Own tests on an quite slow i7-16GB laptop show that the failures seem sporadic (not sure though)

* possibly some **test-timeouts** end up in problems on slower machines
* possibly a **full** clean-up (processes, data-dirs) is needed for some of the tests

## Priority

This issue should get a quite high priority (similar to e.g. build-system-stabilization, like #4923)

## Subtasks

(I am currently at this. Anyone can jump in and provide the logs, ideally as file attachments to this issue)

- [ ] Find out if the failures occur always at the same tests
- [ ] Find out if the failures occur when test is run alone (ctest -R test-name)
- [ ] Produce test-logs
- [ ] Get feedback from core-devs

Currently using within eos/build:

`ctest -VV --output-on-failure -E 'unit_test_binaryen|unit_test_wavm|restart-scenarios' > 1.log`

(excluding `binaryen` and `wavm` which pass, but take long. Excluding `restart-scenarios*` tests, which seem to always fail currently)

### Full Test-Sequence

ubuntu 18.04, fresh install (Native, Virtual or WSL), then

```bash
sudo apt update
sudo apt upgrade
# fetch repo & submodules
./eosio_build.sh
# launch mongodb, as instructed
cd build
cmake --output-on-failure
```

(it seems `apt update/upgrade` is not deterministic, but ignoring for now)

**Comment by lazaridiscom** [comment]
The good news: test pass now (version 1.1.3)

The bad news: `Total Test time (real) = 3557.49 sec` - obviously, I need a new machine.

```bash
100% tests passed, 0 tests failed out of 41

Label Time Summary:
long_running_tests    = 1301.26 sec*proc (2 tests)

Total Test time (real) = 3557.49 sec

laz@laz-vb:~/eos/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
laz@laz-vb:~/eos/build$ 
```

**Comment by jgiszczak** [comment]
The long running tests will always take a considerable amount of time as they are dependent on wall clock time.  Several of the tests not in the long running section are also dependent on real time.

**Comment by lazaridiscom** [comment]
Ah, I see. Thanks for clarifying.

(But I guess I'll need anyway a classy workstation to minimize build-times)

**Comment by lazaridiscom** [comment]
@brianjohnson5972 , can you please reopen #5036, as I'm still getting errors (1 of 5 runs) ?
