### ISSUE TITLE
[TASK] Simplify Newcomer Entry

### ISSUE THREAD

**Issue by lazaridiscom** [EOSIO/eos#5014]
(draft)

## Goal

Newcomers to eosio should be able to enter in a simple and barrier-free manner. It should be an overall positive experience. 

This affects newcomers like:
* simple casual users
* Evaluators
* dapp-developers
* interested contributors (who would like to contribute to eos code).

## Barriers to Entry

There are several barriers within different subsystems (build, test, documentation etc.).

Some example issues (note: some of the closed issues are still relevant) : 

https://github.com/EOSIO/eos/issues?utf8=%E2%9C%93&q=+author%3Alazaridiscom+

## Execution

EOS Core-Developers are busy with... core-work, especially now, where the system has went live. They should not get distracted with this very annoying "make things simple" stuff, which can be very exhausting.

This task should be executed by folks new to the domain, but experienced enough in general (senior or 'admiral' grade) to deal with this combined product/project-management task.

## Sub-tasks
=> spot barriers and remove them, then update docs

- [x] - #5133 [REGRESSION] [FIX] eosiocpp library problems
- [x] - #5126 [CRITICAL] "Hello World" Tutorial is Broken
- [ ] - Provide Quick-Starts right within the README
- [ ] - Ensure Documentation is in Synch

### Advanced

- [ ] - #4923 [BUILD] Unify Docker Build-Scripts 
- [ ] - #4984 [TEST] Unify CI Tests with Local Tests 
- [ ] - Create Docker Starter Repo

## User Comments

> https://github.com/EOSIO/eos/issues/5091#issuecomment-411211790 I'm struggling with the same, its very hard to get all of Eos working on my Mac. Even with docker this is a frustrating experience of try and error

**Comment by lazaridiscom** [comment]
Closing, as advanced issues (#4923, #4984) were closed anyways
